site_name: Gluu Docs
site_description: Documenation for Gluu Server
site_favicon: '/img/gluu_favicon.ico'
copyright: Copyright &copy; 2016, Gluu, Inc.
docs_dir: source
repo_url: https://github.com/GluuFederation/docs-3
theme_dir: theme
extra:
    version: '3.0.0'
    logo: 'gluu.jpg'
markdown_extensions:
- admonition
- toc:
     permalink: '#'
pages:
- Home: 'index.md'
- Installation Guide:
        - 'Preparing VM': 'installation-guide/index.md'
        - 'Install Gluu Server': 'installation-guide/install.md'
        - 'Setup Script Options': 'installation-guide/setup_py.md'
#        - 'Cluster with CE': 'installation-guide/cluster.md'
#- Upgrade/Patch Guide:
#        - 'Upgrade Gluu Server' : 'upgrade/index.md'
#        - 'Patch Gluu Server' : 'upgrade/update.md'
- Administration Guide:
    - 'Gluu Server UI' : 'admin-guide/oxtrust-ui.md'
    - 'SSO Protocols' : 'admin-guide/auth-protocol.md'
    - 'Authentication Management' : 'admin-guide/auth-management.md'
    - 'User Authentication' : 'admin-guide/multi-factor-auth.md'
    - 'User Management' : 'admin-guide/user-group.md'
    - 'Log Management' : 'admin-guide/logs.md'
#    - 'Gluu for Mobile' : 'admin-guide/mobile.md'
#    - 'Self-Services for Users' : 'admin-guide/self-service.md'
    - 'OpenID Clients' : 'admin-guide/clients.md'
    - 'SAML SSO' : 'admin-guide/saml.md'
    - 'OAuth2 Grants' : 'admin-guide/oauth2.md'
    - 'OpenID Connect' : 'admin-guide/openid-connect.md'
    - 'UMA' : 'admin-guide/uma.md'
    - 'Attribute Management' : 'admin-guide/attribute.md'
    - 'SCIM protected by UMA' : 'admin-guide/scim-uma.md'
    - 'Gluu Server APIs' : 'admin-guide/api.md'
    - 'SCIM API Configuration' : 'admin-guide/scim.md'
    - 'Backup Gluu Server CE' : 'admin-guide/backup.md'
    - 'Custom Script in Gluu CE' : 'admin-guide/custom-script.md'
    - 'Certificate Management' : 'admin-guide/certificate.md'
#    - 'Fine Tuning Gluu Server' : 'admin-guide/fine-tuning.md'
    - 'FAQ & Troubleshooting' : 'admin-guide/faq.md'
- Integration Guide:
#    - 'Integration in Gluu Server': 'integration/index.md'
    - 'SAML SP': 'integration/saml-sp.md'
    - 'OpenIDC RP': 'integration/openidc-rp.md'
#    - 'OXD OAuth2': 'integration/oauth2.md'
#    - 'Google SSO': 'integration/google.md'
#    - 'Office 365': 'integration/office.md'
#    - 'Hobsons Education Sol': 'integration/hobsons.md'
#    - 'Salesforce': 'integration/salesforce.md'
#    - 'Dropbox': 'integration/dropbox.md'

